version: "3.9"
services:
  db:
    image: mariadb:10.5.4
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oraksil

  mq:
    image: rabbitmq:3.8.5-management
    volumes:
      - ./data/mq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: oraksil
      RABBITMQ_DEFAULT_PASS: oraksil

  turn:
    image: instrumentisto/coturn
    command:
      - -n
      - --log-file=stdout
      - --external-ip="$$(detect-external-ip)"
      - --verbose
      - --fingerprint
      - --realm=oraksil
      - --use-auth-secret
      - --static-auth-secret=oraksil-turn-secret
    ports:
      - "3478:3478"
      - "3478:3478/udp"

