version: "3.9"
services:
  azumma:
    image: sangwonl/azumma
    ports:
      - "8000:8000"
    environment:
      DB_URI: oraksil:oraksil@(db:3306)/oraksil?parseTime=true
      MQRPC_URI: amqp://oraksil:oraksil@mq:5672/
      MQRPC_NAMESPACE: oraksil
      MQRPC_IDENTIFIER: azumma-local
      STATIC_ORAKKI_ID: orakki-static
      TURN_SECRET_KEY: oraksil-turn-secret
      TURN_TTL: "3600"
    depends_on:
      - orakki

  esekki:
    image: sangwonl/esekki
    ports:
      - "3000:3000"
    depends_on:
      - azumma

  gipan:
    image: sangwonl/gipan
    volumes:
      - ./roms:/home/app/roms
    environment:
      IPC_IMAGE_FRAMES: tcp://0.0.0.0:8765
      IPC_SOUND_FRAMES: tcp://0.0.0.0:8766
      IPC_CMD_INPUTS: tcp://0.0.0.0:8767
      RESOLUTION: "640x480"
      FPS: "25"
      KEYFRAME_INTERVAL: "200"
      GAME: dino

  orakki:
    image: sangwonl/orakki
    environment:
      MQRPC_URI: amqp://oraksil:oraksil@mq:5672/
      MQRPC_NAMESPACE: oraksil
      MQRPC_IDENTIFIER: orakki-static
      STATIC_ORAKKI_ID: orakki-static
      PLAYER_HEALTHCHECK_TIMEOUT: "20"
      PLAYER_HEALTHCHECK_INTERVAL: "3"
      PLAYER_IDLECHECK_TIMEOUT: "1200"
      PLAYER_IDLECHECK_INTERVAL: "7"
      TURN_URI: turn:turn:3478?transport=tcp
      TURN_SECRET_KEY: oraksil-turn-secret
      TURN_TTL: "3600"
      IPC_IMAGE_FRAMES: tcp://gipan:8765
      IPC_SOUND_FRAMES: tcp://gipan:8766
      IPC_CMD_INPUTS: tcp://gipan:8767
    depends_on:
      - gipan
